{"file":"C:\\Users\\eudre\\OneDrive\\Desktop\\Projetos\\pgben\\pgben-server\\src\\modules\\configuracao\\exceptions\\integracao-teste.exception.ts","mappings":";;;AAAA,2CAAqD;AAErD;;;GAGG;AACH,MAAa,wBAAyB,SAAQ,4BAAmB;IAC/D;;;;OAIG;IACH,YAAY,MAAc,EAAE,MAAc;QACxC,KAAK,CAAC,wBAAwB,MAAM,aAAa,MAAM,EAAE,CAAC,CAAC;IAC7D,CAAC;CACF;AATD,4DASC","names":[],"sources":["C:\\Users\\eudre\\OneDrive\\Desktop\\Projetos\\pgben\\pgben-server\\src\\modules\\configuracao\\exceptions\\integracao-teste.exception.ts"],"sourcesContent":["import { BadRequestException } from '@nestjs/common';\n\n/**\n * Exceção lançada quando um teste de integração falha.\n * Estende a BadRequestException padrão do NestJS com mensagem personalizada.\n */\nexport class IntegracaoTesteException extends BadRequestException {\n  /**\n   * Cria uma nova instância da exceção.\n   * @param codigo - Código da integração\n   * @param motivo - Motivo da falha\n   */\n  constructor(codigo: string, motivo: string) {\n    super(`Teste de integração '${codigo}' falhou: ${motivo}`);\n  }\n}\n"],"version":3}